### model
model_name_or_path: "{{model_name_or_path}}"
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: "{{lora_rank}}"
lora_target: "{{lora_target}}"
lora_alpha: "{{lora_alpha}}"

### dataset
dataset: "{{train_dataset_name}}"
template: "{{template}}"
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: "{{output_dir}}"
logging_steps: 2
save_steps: 20
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: "{{per_device_train_batch_size}}"
gradient_accumulation_steps: "{{gradient_accumulation_steps}}"
learning_rate: "{{learning_rate}}"
num_train_epochs: "{{num_train_epochs}}"
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: reward-sentiment