bf16: true
cutoff_len: 2048
dataset: mental-healer_reward-sentiment_train
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 16
learning_rate: 2.0e-05
logging_steps: 2
lora_alpha: 128
lora_rank: 64
lora_target: all
lr_scheduler_type: cosine
max_samples: 100000
model_name_or_path: /scratch/prj/charnu/seacow_hf_cache/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
num_train_epochs: 5.0
output_dir: /scratch/prj/charnu/ft_weights/mental-healer/reward-sentiment/llama8
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
report_to: wandb
run_name: reward-sentiment
save_steps: 20
stage: sft
template: llama3
trust_remote_code: true
warmup_ratio: 0.1
